### ISSUE TITLE
PA Review: Menus

### ISSUE THREAD

**Issue by Numie** [Numie/FoodDotCom#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by BCrawfordScott** [comment]
- [ ] Landing page search bar is unresponsive depending on order of clicks.  This likely has to do with the dropdown, but currently it seems it does not always search immediately when you click on find food if you accidentally hit enter instead of manually selecting an address from the dropdown.
- [x] Update the styling for menu items.  It would be nice if they were in two columns instead of just one.
- [x] Should order bag persist through changing restaurants?
- [ ] Possible to allow for dummy input of information that doesn't persist?  Obviously no CC info.  Maybe instead of inputting payment info it simply directs to an order complete page with a summary of the order and an estimated delivery time.

Really fantastic work

**Comment by Numie** [comment]
- Fixed order persisting bug last night already.
- Fixed menu items becoming one column when browser window shrinks
- Looking into search bar issues...likely related to Google maps API limits
